#!/usr/bin/env bash
echo_run(){
  echo -e "\e[32m\$ $*\e[0m"
  "$@"
}

echo_run sudo -i nix upgrade-nix

if [ "$(uname)" = "Darwin" ]; then
  echo_run nix flake update ~/.config/nix-darwin
  echo_run darwin-rebuild changelog
  echo_run darwin-rebuild switch --flake ~/.config/nix-darwin
fi

echo_run nix flake update ~/.config/home-manager
echo_run home-manager switch
