#!/bin/bash
cd "$HOME"

mkdir -p .ssh
ssh-keyscan github.com >> ~/.ssh/known_hosts 2>&1 | grep -v '^#'
chmod 700 .ssh
chmod 600 .ssh/*

yadm remote set-url origin "git@github.com:pkoch/yadm.git"
yadm submodule update --recursive --init

~/.apt.sh || echo 1>&2 '!!! Unable to apt install'

asdf plugin-add gh https://github.com/pkoch/asdf-gh.git
cat .tool-versions  | awk '{print $1}' | grep -v '^gh$' | xargs -I= asdf plugin-add =
asdf install

. .profile

# Make vim not complain about input and output
script -qc "vim '+PlugUpdate' '+PlugClean"'!'"' '+qall'" /dev/null

# Require GPG key to be loaded, or abort with instructions.
if ! has_private_key; then
  echo 1>&2 '!!! You need the private key loaded to proceed with the rest of the bootstartp.'
  echo 1>&2 '!!! Get the key in place (make sure it shows up on gpg -K) and run this script again.'
  exit 1
fi

(cd secrets && git crypt unlock)

. ~/.config/yadm/update
