#!/usr/bin/env bash
cd "$HOME"

mkdir -p .ssh/controlmasters
ssh-keyscan github.com | grep -v '^#' 2>&1 >> ~/.ssh/known_hosts
chmod 700 .ssh
chmod 600 .ssh/*
chmod 700 .ssh/controlmasters

yadm remote set-url origin "git@github.com:pkoch/yadm.git"
yadm submodule update --recursive --init

. .profile

# Make vim not complain about input and output
script -qc "vim '+PlugUpdate' '+PlugClean"'!'"' '+qall'" /dev/null

# Require GPG key to be loaded, or abort with instructions.
. .profile.d/ZZ-gpg
if ! has_private_key; then
  echo 1>&2 '!!! You need the private key loaded to proceed with the rest of the bootstartp.'
  echo 1>&2 '!!! Get the key in place (make sure it shows up on gpg -K) and run this script again.'
  exit 1
fi

(cd secrets && git crypt unlock)

. ~/.config/yadm/update
