#!/usr/bin/env bash

message(){
  echo -e "\e[34m"$@"\e[0m"
}

message '# Initial state'
yadm status -sb

for f in `find .config/yadm/update.d -mindepth 1 -not -name '.*' | sort -n`; do
  message "# $f"
  "$f"
done; unset f

message '# Final state'
yadm status -sb

date '+%s' > ~/.cache/yadm-update
