#!/bin/bash
echo Initial state
yadm status -sb

if command -v gpg >/dev/null; then
  gpg --import ~/.gnupg/pubring.asc
  gpg --export -a > ~/.gnupg/pubring.asc

  gpg --import-ownertrust ~/.gnupg/ownertrust
  gpg --export-ownertrust | grep -v '^#' > ~/.gnupg/ownertrust
fi

asdf plugin update --all
asdf update

~/bin/yadm-update

echo Final state
yadm status -sb

date '+%s' > ~/.cache/yadm-update
