#!/usr/bin/env bash
SEVEN_DAYS_IN_SECONDS=604800

if ! [ -r "$HOME/.cache/yadm-update" ]; then
  echo >&2 '! No yadm-update file. You seem to not have finished the bootstrap.'
  echo >&2 '! Run `. ~/.config/yadm/bootstrap` to fix this.'
  return 1
fi

if ! [ "$(bc <<<"$(date '+%s') - $SEVEN_DAYS_IN_SECONDS")" -lt "$(cat "$HOME/.cache/yadm-update")" ]; then
  echo >&2 '~/.config/yadm/update # Time has come.'
  return 1
fi
