#!/bin/bash
check_yadm_update() {
  if ! [ -r "$HOME/.cache/yadm-update" ]; then
    echo >&2 '! No yadm-update file. You seem to not have finished the bootstrap.'
    echo >&2 '! Run `. .config/yadm/bootstrap` to fix this.'
    return 1
  fi

  if ! [ "$(date --date '7 days ago' '+%s')" -lt "$(cat "$HOME/.cache/yadm-update")" ]; then
    echo >&2 '! You have not updated things in a while.'
    echo >&2 '! Run `. .config/yadm/update` to fix this.'
    return 1
  fi
}
check_yadm_update
unset check_yadm_update
